#!/usr/bin/env python3

import os
import sys

db_file = "db/waypoint.db"

if os.path.exists(db_file):
    os.remove(db_file)

os.system("sqlite3 db/waypoint.db < db/sql/WaypointDBCreation.sql")
os.system("sqlite3 db/waypoint.db < db/sql/SampleData.sql")

if len(sys.argv) == 2 and sys.argv[1] == "open":
    os.system("sqlite3 db/waypoint.db")
